# Generated by Django 4.2 on 2024-11-12 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('image', models.ImageField(blank=True, default='../default_post_x1mf4x', upload_to='images/')),
                ('category', models.CharField(blank=True, choices=[('family-and-friends', 'Family and Friends'), ('everyday-life-&-candid-moments', 'Everyday Life & Candid Moments'), ('nature-and-landscapes', 'Nature and Landscapes'), ('cityscapes-and-architecture', 'Cityscapes and Architecture'), ('food-and-drinks', 'Food and Drinks'), ('people-and-portraits', 'People and Portraits'), ('fashion-and-style', 'Fashion and Style'), ('travel-and-adventure', 'Travel and Adventure'), ('art-and-creativity', 'Art and Creativity'), ('fitness-and-health', 'Fitness and Health'), ('technology-and-gadgets', 'Technology and Gadgets'), ('pets-and-animals', 'Pets and Animals'), ('events-and-celebrations', 'Events and Celebrations'), ('abstract-and-conceptual', 'Abstract and Conceptual'), ('seasonal-and-holiday', 'Seasonal and Holiday'), ('vintage-and-retro', 'Vintage and Retro'), ('self-portraits', 'Self-Portraits'), ('street-photography', 'Street Photography'), ('relationships', 'Relationships'), ('other', 'Other')], default=None, max_length=150, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
