# Generated by Django 3.2.25 on 2024-12-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('family-and-friends', 'Family and Friends'), ('everyday-life-&-candid-moments', 'Everyday Life & Candid Moments'), ('nature-and-landscapes', 'Nature and Landscapes'), ('cityscapes-and-architecture', 'Cityscapes and Architecture'), ('food-and-drinks', 'Food and Drinks'), ('people-and-portraits', 'People and Portraits'), ('fashion-and-style', 'Fashion and Style'), ('travel-and-adventure', 'Travel and Adventure'), ('art-and-creativity', 'Art and Creativity'), ('fitness-and-health', 'Fitness and Health'), ('technology-and-gadgets', 'Technology and Gadgets'), ('pets-and-animals', 'Pets and Animals'), ('events-and-celebrations', 'Events and Celebrations'), ('abstract-and-conceptual', 'Abstract and Conceptual'), ('seasonal-and-holiday', 'Seasonal and Holiday'), ('vintage-and-retro', 'Vintage and Retro'), ('self-portraits', 'Self-Portraits'), ('street-photography', 'Street Photography'), ('relationships', 'Relationships'), ('other', 'Other')], max_length=150, null=True),
        ),
    ]
