# Generated by Django 3.2.4 on 2024-10-31 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_post_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('category', models.CharField(choices=[('spam', 'Spam'), ('inappropriate_content', 'Inappropriate Content'), ('harassment', 'Harassment or Bullying'), ('hate_speech', 'Hate Speech'), ('misinformation', 'Misinformation'), ('copyright_violation', 'Copyright Violation'), ('impersonation', 'Impersonation'), ('self_harm', 'Self-harm or Suicide'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'user')},
            },
        ),
    ]
