# Generated by Django 4.2 on 2024-11-07 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_auto_20241031_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
