# Generated by Django 4.2 on 2024-11-11 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_post_mentioned_users'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='unique_report_per_user_post',
        ),
        migrations.AddField(
            model_name='report',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('spam', 'Spam'), ('inappropriate_content', 'Inappropriate Content'), ('harassment', 'Harassment or Bullying'), ('hate_speech', 'Hate Speech'), ('misinformation', 'Misinformation'), ('copyright_violation', 'Copyright Violation'), ('impersonation', 'Impersonation'), ('self_harm', 'Self-harm or Suicide'), ('other', 'Other')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('post', 'user')},
        ),
        migrations.RemoveField(
            model_name='report',
            name='reason',
        ),
    ]
