# Generated by Django 4.2 on 2024-11-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_post_mentioned_users_remove_post_tagged_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tagged_user',
        ),
    ]
