# Generated by Django 4.2 on 2024-11-11 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_remove_post_tagged_user'),
        ('report', '0002_report_post_alter_report_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(null='spam', on_delete=django.db.models.deletion.CASCADE, related_name='report', to='posts.post'),
        ),
    ]
