# Generated by Django 3.2.4 on 2024-10-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
