# Generated by Django 3.2.4 on 2024-10-29 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_chat_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
    ]
