# Generated by Django 3.2.4 on 2024-10-30 16:24

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_auto_20241030_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(condition=models.Q(('sender__lt', django.db.models.expressions.F('receiver'))), fields=('sender', 'receiver'), name='unique_chat_between_users'),
        ),
        migrations.RemoveField(
            model_name='chat',
            name='message',
        ),
    ]
