# Generated by Django 3.2.4 on 2024-10-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0016_auto_20241030_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
